### ISSUE TITLE
Está publicada?

### ISSUE THREAD

**Issue by lsmar** [renatojdev/bancointer-python#1]
@renatojdev você chegou a publicar a lib no pypi? Não achei.

**Comment by renatojdev** [comment]
Olá Ismar, como vai? Acabei não publicando lá ainda, mas no README tem as instruções para instalar localmente. Abraço.

**Comment by renatojdev** [comment]
@lsmar o projeto foi publicado no PyPi.. Disponível para utilizar com `pip install bancointer-python`.
