### ISSUE TITLE
No module named 'decouple'

### ISSUE THREAD

**Issue by nagualcode** [renatojdev/bancointer-python#2]
ao rodar o exemplo boleto.py

    from decouple import config
ModuleNotFoundError: No module named 'decouple'

**Comment by nagualcode** [comment]
pip install python-decouple

**Comment by jfsts** [comment]
Boa tarde. 
Quando utilizo a baixa, está dando o erro :
"requests.exceptions.MissingSchema: Invalid URL 'Noneboletos/00714656116/cancelar': No scheme supplied. Perhaps you meant http://Noneboletos/00714656116/cancelar?"

Quando uso config("X-INTER-CONTA-CORRENTE"), cert)
O erro:
    config("X-INTER-CONTA-CORRENTE"), cert)
NameError: name 'cert' is not defined
